2022-08-17 15:10:21.905 ERROR (MainThread) [root] A message handler raised an exception: '/org/bluez/hci0/dev_63_43_D7_49_EB_E4'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 668, in _process_message
    result = handler(msg)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 711, in _parse_msg
    del self._properties[obj_path][interface]
KeyError: '/org/bluez/hci0/dev_63_43_D7_49_EB_E4'

2022-08-17 15:10:43.518 ERROR (MainThread) [homeassistant.components.mjpeg] Timeout getting camera image from iPhone
2022-08-18 11:04:45.132 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data for 192.168.2.102: Timeout waiting for response for <class 'api_pb2.DeviceInfoRequest'>
2022-08-18 16:37:08.685 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data for 192.168.2.102: 
2022-08-18 16:37:50.675 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Hello timed out
2022-08-19 09:32:50.295 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Timeout waiting for response for <class 'api_pb2.ConnectRequest'>
2022-08-19 10:41:59.929 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-doit @ 192.168.2.101: Error connecting to ('192.168.2.101', 6053): [Errno 113] Connect call failed ('192.168.2.101', 6053)
2022-08-19 10:42:00.857 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-doit-temp @ 192.168.2.103: Error connecting to ('192.168.2.103', 6053): [Errno 113] Connect call failed ('192.168.2.103', 6053)
2022-08-19 10:42:03.481 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Error connecting to ('192.168.2.102', 6053): [Errno 113] Connect call failed ('192.168.2.102', 6053)
2022-08-19 10:42:23.459 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>
2022-08-19 10:42:23.480 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>
2022-08-19 22:19:27.911 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 222.100.166.100 (222.100.166.100). Requested URL: '/auth/token'. (Mozilla/5.0 (iPad; CPU OS 12_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1)
2022-08-19 22:19:27.960 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 222.100.166.100 (222.100.166.100). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPad; CPU OS 12_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1)
2022-08-19 23:30:01.064 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 222.100.166.100 (222.100.166.100). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022-08-19 23:30:01.439 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 222.100.166.100 (222.100.166.100). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022-08-21 17:16:52.417 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-22 18:11:04.036 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-23 12:43:25.571 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.2.14 (192.168.2.14). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022-08-23 12:43:25.857 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.2.14 (192.168.2.14). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
2022-08-23 18:17:26.044 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-24 11:03:12.139 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Error connecting to ('192.168.2.102', 6053): [Errno 111] Connect call failed ('192.168.2.102', 6053)
2022-08-24 17:39:42.950 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Error connecting to ('192.168.2.102', 6053): [Errno 111] Connect call failed ('192.168.2.102', 6053)
2022-08-24 17:42:51.800 ERROR (MainThread) [homeassistant.components.mjpeg] Error getting new camera image from iPhone: Cannot connect to host 192.168.2.13:80 ssl:default [Connect call failed ('192.168.2.13', 80)]
2022-08-24 19:18:44.660 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-25 06:36:36.749 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data for 192.168.2.102: Timeout waiting for response for <class 'api_pb2.DeviceInfoRequest'>
2022-08-25 11:40:23.928 ERROR (MainThread) [homeassistant.components.mjpeg] Error getting new camera image from iPhone: Cannot connect to host 192.168.2.13:80 ssl:default [Connect call failed ('192.168.2.13', 80)]
2022-08-25 11:40:56.921 ERROR (MainThread) [homeassistant.components.mjpeg] Error getting new camera image from iPhone: Cannot connect to host 192.168.2.13:80 ssl:default [Connect call failed ('192.168.2.13', 80)]
2022-08-25 12:10:42.308 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Timeout during handshake
2022-08-25 12:14:01.495 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Timeout during handshake
2022-08-25 17:01:53.778 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Error connecting to ('192.168.2.102', 6053): [Errno 111] Connect call failed ('192.168.2.102', 6053)
2022-08-25 17:19:59.702 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-cam @ 192.168.2.102: Error connecting to ('192.168.2.102', 6053): [Errno 111] Connect call failed ('192.168.2.102', 6053)
2022-08-27 11:23:26.329 ERROR (MainThread) [homeassistant.components.mjpeg] Error getting new camera image from iPhone: Cannot connect to host 192.168.2.13:80 ssl:default [Connect call failed ('192.168.2.13', 80)]
2022-08-27 11:24:41.177 ERROR (MainThread) [homeassistant.components.mjpeg] Error getting new camera image from iPhone: Cannot connect to host 192.168.2.13:80 ssl:default [Connect call failed ('192.168.2.13', 80)]
2022-08-27 16:26:45.114 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
